baseURL = "/"
title = "mmanuelubah"
languageCode = "en-us"
theme = "hello-friend-ng"
pagination.pagerSize = 10

# Theme Parameters
[params]
  title = "mmanuelubah"
  description = "MindOnChain is a blog that explores blockchain analytics, airdrops, and decentralized innovation — written by Emmanuel."
  avatar = "images/Avatar.png"                  # Path: /static/images/Avatar.png
  enableSharingButtons = true
  enableGlobalLanguageMenu = true
  enableThemeToggle = true
  customCSS = ["/css/design-system.css", "/css/custom.css"]
  defaultTheme = "dark"
  showPostsOnHomePage = true
  numberOfPostsOnHomePage = 3
  ownerNameDisplay = "Ubanatu Chinaza Emmanuel"
  ownerNameMeaning = "Ubanatu means 'honour/nobility'; Chinaza means 'God answers'; Emmanuel means 'God is with us'."
  ownerNameTooltip = true

[params.passwords]
  default = "bf9b5951c550f519c08a4515282f5dc69e0a9e55152d5d316570436b9fa101dc" # SHA-256 for "emmanuel"

[build]
  writeStats = true

# Logo
[params.logo]
  logoHomeLink = "/"
  logoImage = "images/IMG_4493.jpeg"   # Path: /static/images/favicon-logo-96x96.png

# Favicon
[params.assets]
  favicon = "images/Avatar.png"                # Path: /static/images/favicon.ico

# Footer Section
[params.footer]
  copyright = "© 2025 Emmanuel"

# Social Links
[params.social]
  github = "https://github.com/mmanuelubah"
  linkedin = "https://www.linkedin.com/in/chinaza-ubanatu-05a983184/"
  twitter = "https://x.com/mmanuelubah"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Menu Navigation
[menu]

