[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.125.4" # replace with your Hugo version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
